### ISSUE TITLE
Production error: ValueError: invalid day number provided in cftime.Datetime360Day

### ISSUE THREAD

**Issue by agstephens** [roocs/clisops#151]
* clisops version: production
* Python version: 3.7
* Operating System: Centos7

### Description

This time we have a clisops error when working on inputs:

```
File: /badc/cmip6/data/CMIP6/ScenarioMIP/NIMS-KMA/KACE-1-0-G/ssp585/r1i1p1f1/Amon/
tas/gr/v20190920/tas_Amon_KACE-1-0-G_ssp585_r1i1p1f1_gr_201501-210012.nc

Subset args:
{'area':  (-10.0, 30.0, 35.0, 70.0), 
'level': None, 
'time': ('2021-01-01T00:00:00', '2050-12-31T00:00:00'), 
'output_type': 'netcdf', 
'output_dir': '/gws/nopw/j04/cp4cds1_vol1/wps/prod/tmp/rook/pywps_process_kh9f35xw/subset_ouaz2kfn',
'split_method': 'time:auto', 
'file_namer': 'standard'}

Error:
$ cat /gws/nopw/j04/cp4cds1_vol1/wps/prod/tmp/rook/pywps_process_kh9f35xw/job-error.txt

/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/clisops/core/subset.py:888: UserWarning: "start_date" has been nudged to nearest valid time step in
 xarray object.
  da = subset_time(da, start_date=start_date, end_date=end_date)
/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/clisops/core/subset.py:888: UserWarning: "end_date" has been nudged to nearest valid time step in x
array object.
  da = subset_time(da, start_date=start_date, end_date=end_date)
Traceback (most recent call last):
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/clisops/core/subset.py", line 93, in func_checker
    sel_time = da.time.sel(time=kwargs["end_date"])
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/xarray/core/dataarray.py", line 1259, in sel
    **indexers_kwargs,
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/xarray/core/dataset.py", line 2231, in sel
    self, indexers=indexers, method=method, tolerance=tolerance
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/xarray/core/coordinates.py", line 417, in remap_label_indexers
    obj, v_indexers, method=method, tolerance=tolerance
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/xarray/core/indexing.py", line 270, in remap_label_indexers
    idxr, new_idx = convert_label_indexer(index, label, dim, method, tolerance)
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/xarray/core/indexing.py", line 191, in convert_label_indexer
    indexer = index.get_loc(label_value, method=method, tolerance=tolerance)
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/xarray/coding/cftimeindex.py", line 458, in get_loc
    return self._get_string_slice(key)
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/xarray/coding/cftimeindex.py", line 422, in _get_string_slice
    parsed, resolution = _parse_iso8601_with_reso(self.date_type, key)
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/xarray/coding/cftimeindex.py", line 128, in _parse_iso8601_with_reso
    return default.replace(**replace), resolution
  File "src/cftime/_cftime.pyx", line 1006, in cftime._cftime.datetime.replace
  File "src/cftime/_cftime.pyx", line 1681, in cftime._cftime.Datetime360Day.__init__
  File "src/cftime/_cftime.pyx", line 908, in cftime._cftime.datetime.__init__
  File "src/cftime/_cftime.pyx", line 1347, in cftime._cftime.assert_valid_date
ValueError: invalid day number provided in cftime.Datetime360Day(2050, 12, 31, 0, 0, 0, 0)

```

It looks like it a calendar-related issue, the data is on 360_day calendar but the request includes an invalid date: 2050-12-31

We want clisops to accept this and nudge it into range.

@ellesmith88: please take a look

**Comment by agstephens** [comment]
@ellesmith88: here is a suggested approach, it should have the building blocks you could interact with when doing a `try/except` on creating each datetime for a set calendar:

```
import re


class AnyCalendarDateTime:

    # MAX_DAY - is defined as the maximum number of days in any month
    #           in any of the calendars supported by cftime
    MAX_DAY = 31
    MIN_DAY = 1
    MAX_MONTH = 12
    MIN_MONTH = 1

    def __init__(self, year, month, day, hour, minute, second):
        self.year = year
        self.month = month
        self.day = day
        self.hour = hour
        self.minute = minute
        self.second = second

    def __repr__(self):
        return self.value

    @property
    def value(self):
        return f"{self.year}-{self.month:02d}-{self.day:02d}" \
               f"T{self.hour:02d}:{self.minute:02d}:{self.second:02d}"

    def add_day(self):
        self.day += 1

        if self.day > self.MAX_DAY:
            self.month += 1
            self.day = 1

        if self.month > self.MAX_MONTH:
            self.year += 1
            self.month = self.MIN_MONTH 
            
    def sub_day(self, n=1):
        self.day -= 1

        if self.day < self.MIN_DAY:
            self.month -= 1
            self.day = self.MAX_DAY

        if self.month < self.MIN_MONTH:
            self.year -= 1
            self.month = self.MAX_MONTH 


def str_to_AnyCalendarDateTime(dt):
    """
    Takes a string representing date/time and returns a DateTimeAnyTime object.
    String formats should start with Year and go through to Second, but you
    can miss out anything from month onwards.

    :param dt: string representing a date/time [string]
    :return: AnyCalendarDateTime object
    """
    if len(dt) < 1:
        raise Exception("Must provide at least the year as argument to create date time.")

    # Start with most common pattern
    regex = re.compile(r"^(\d+)-(\d+)-(\d+)[T ](\d+):(\d+):(\d+)$")
    match = regex.match(dt)

    if match:
        items = match.groups()
    else:
        # Try a more complex split and build of the time string.
        defaults = [-1, 1, 1, 0, 0, 0]
        components = re.split("[- T:]", dt)

        # Build a list of time components
        items = components + defaults[len(components):]

    return AnyCalendarDateTime(*[int(i) for i in items])


import cftime

def test_AnyCalendarDateTime():
    d = str_to_AnyCalendarDateTime('1999-01-31')
    d.sub_day()
    assert(d.value.startswith('1999-01-30'))

    d.add_day()
    d.add_day()
    assert(d.value.startswith('1999-02-01'))

    d = str_to_AnyCalendarDateTime('1999-01-33')
    d.sub_day()
    d.sub_day()
    assert(d.value.startswith('1999-01-31'))

    d = str_to_AnyCalendarDateTime('1999-01-01T12:13:14')
    d.sub_day()
    assert(d.value == '1998-12-31T12:13:14')


test_AnyCalendarDateTime()
```

**Comment by agstephens** [comment]
@ellesmith88 note: if you use this approach, please double-check the _real_ value for `MAX_DAY` - i.e. the max across all months in all calendar types.

**Comment by ellesmith88** [comment]
@agstephens I'm happy to go with this, do you think `AnyCalendarDateTime` and `str_to_AnyCalendarDateTime` should live in `roocs_utils`?

**Comment by agstephens** [comment]
@ellesmith88 I suspect that they should, it makes most sense to keep them generic, maybe in a new `time_utils.py` module?

Please add a number of quick tests to make sure I haven't implemented anything daft in the above code ;-)

**Comment by ellesmith88** [comment]
@agstephens Perfect, that's what I was thinking, I'll put them there! Yes, working on it :)

**Comment by ellesmith88** [comment]
closed by roocs/roocs-utils#67 and #153
