### ISSUE TITLE
Can we modify check on start and end datetimes in "clisops.core.subset"?

### ISSUE THREAD

**Issue by agstephens** [roocs/clisops#71]
### Description

The checks in `subset_time` can raise an exception in certain cases:

I have tested:

- start: None, end: None --> defaults to: time.min(), time.max()
- start: value in array, end: value in array --> uses provided values

However, if `start_date` or `end_date` are **in the time range BUT are not exactly aligned then we get an exception**, e.g.:

- valid times: ['2075-12-01T12', '2075-12-02T12', '2075-12-03T12']
- start_date: '2075-12-02T00' - in range but not exactly in the time array
- result: 

```
Traceback (most recent call last):
  File "test_start_datetime.py", line 7, in <module>
    res = subset_time(ds, start_date=ts[0], end_date=ts[1])
  File "/home/users/astephen/roocs/clisops/clisops/core/subset.py", line 78, in func_checker
    > da.time.sel(time=kwargs["end_date"]).max()
  File "/home/users/astephen/roocs/venv/lib/python3.7/site-packages/xarray/core/common.py", line 46, in wrapped_func
    return self.reduce(func, dim, axis, skipna=skipna, **kwargs)
  File "/home/users/astephen/roocs/venv/lib/python3.7/site-packages/xarray/core/dataarray.py", line 2338, in reduce
    var = self.variable.reduce(func, dim, axis, keep_attrs, keepdims, **kwargs)
  File "/home/users/astephen/roocs/venv/lib/python3.7/site-packages/xarray/core/variable.py", line 1591, in reduce
    data = func(input_data, **kwargs)
  File "/home/users/astephen/roocs/venv/lib/python3.7/site-packages/xarray/core/duck_array_ops.py", line 324, in f
    return func(values, axis=axis, **kwargs)
  File "/home/users/astephen/roocs/venv/lib/python3.7/site-packages/xarray/core/nanops.py", line 86, in nanmax
    return _nan_minmax_object("max", dtypes.get_neg_infinity(a.dtype), a, axis)
  File "/home/users/astephen/roocs/venv/lib/python3.7/site-packages/xarray/core/nanops.py", line 67, in _nan_minmax_object
    data = getattr(np, func)(filled_value, axis=axis, **kwargs)
  File "<__array_function__ internals>", line 6, in amax
  File "/home/users/astephen/roocs/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2706, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/home/users/astephen/roocs/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

Here is a suggested rewrite of the `check_start_end_dates` decorator, use slicing to _nudge_ the `start_date` and `end_date`, e.g.:

```
def check_start_end_dates(func):
    @wraps(func)
    def func_checker(*args, **kwargs):
        da = args[0]

        kwargs.setdefault("start_date", None)
        kwargs.setdefault("end_date", None)

        nudged_start = da.time.sel(time=slice(kwargs["start_date"], None)).values[0].isoformat()
        if nudged_start != kwargs["start_date"]:
            warnings.warn(
                '"start_date" not found within input date time range. Value has been nudged to nearest'
                ' valid time step in xarray object.',
            UserWarning,
            stacklevel=2,
            )
            kwargs["start_date"] = nudged_start

        nudged_end = da.time.sel(time=slice(None, kwargs["end_date"])).values[-1].isoformat()
        if nudged_end != kwargs["start_date"]:
            warnings.warn(
                '"end_date" not found within input date time range. Value has been nudged to nearest'
                ' valid time step in xarray object.',
                UserWarning,
                stacklevel=2,
                )
            kwargs["end_date"] = nudged_end

        return func(*args, **kwargs)

    return func_checker

```

**Comment by agstephens** [comment]
Forget what I said above, I have back-tracked and made less changes, but I have updated `core.subset` in this change:

https://github.com/roocs/clisops/commit/96aceeccf2937b2261546503c571c89423e65c8e

**Comment by agstephens** [comment]
This has been fixed in clisops.
